/**
 * Exercício 1
 * Criar um aplicativo conforme a imagem abaixo, onde o usuário 
 * deverá digitar quatro notas, a clicar no botão calcular deverá informar a 
 * maior nota a menor nota e a sua mé.dia de aprovação, sendo-se que para ser 
 * aprovado a nota deverá ser maior ou igual a 7, um botão para “limpar” 
 * os campos e o botão “Sair” para finalizar o programa.
 * 
 * @author ferreiraluizga
 */

package mediaAritmetica;

import java.awt.Toolkit;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

public class MediaAritmetica extends javax.swing.JFrame {

    /**
     * Creates new form MediaAritmetica
     */
    public MediaAritmetica() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/mediaAritmetica/img/appIcon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblNota1 = new javax.swing.JLabel();
        txtNota1 = new javax.swing.JTextField();
        txtNota2 = new javax.swing.JTextField();
        lblNota2 = new javax.swing.JLabel();
        txtNota3 = new javax.swing.JTextField();
        lblNota3 = new javax.swing.JLabel();
        lblNota4 = new javax.swing.JLabel();
        txtNota4 = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblMaiorNota = new javax.swing.JLabel();
        lblMenorNota = new javax.swing.JLabel();
        lblMedia = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Média dos Alunos");

        lblTitulo.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Calcular Média");

        lblNota1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblNota1.setText("Insira a 1ª Nota");

        txtNota1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtNota2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblNota2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblNota2.setText("Insira a 2ª Nota");

        txtNota3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblNota3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblNota3.setText("Insira a 3ª Nota");

        lblNota4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblNota4.setText("Insira a 4ª Nota");

        txtNota4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnCalcular.setText("Calcular Média");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        lblMaiorNota.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblMaiorNota.setText("Maior Nota:");

        lblMenorNota.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblMenorNota.setText("Menor Nota:");

        lblMedia.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblMedia.setText("Média do Aluno:");

        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mediaAritmetica/img/limpar.gif"))); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mediaAritmetica/img/sair.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNota1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNota1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNota3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNota3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNota4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNota2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNota2, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(txtNota4, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))))
                .addGap(12, 12, 12))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMenorNota)
                            .addComponent(lblMaiorNota)
                            .addComponent(lblMedia))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSair)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTitulo)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNota1)
                    .addComponent(txtNota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNota2)
                    .addComponent(txtNota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNota3)
                    .addComponent(txtNota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNota4)
                    .addComponent(txtNota4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(btnCalcular)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMaiorNota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMenorNota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMedia)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpar)
                    .addComponent(btnSair))
                .addGap(12, 12, 12))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        double n1, n2, n3, n4, media; //vaiaveis para atribuir notas inseridas e calcular media
        DecimalFormat mascara = new DecimalFormat("#.##"); //mascara para formatar resultado final em até duas casas decimais
        
        //caso o usuário deixe um campo vazio, a nota 0 será atribuida automaticamente
        if(txtNota1.getText().equals("")){
            txtNota1.setText("0.0");
        }
        if(txtNota2.getText().equals("")){
            txtNota2.setText("0.0");
        }
        if(txtNota3.getText().equals("")){
            txtNota3.setText("0.0");
        }
        if(txtNota4.getText().equals("")){
            txtNota4.setText("0.0");
        }
        
        //atribuição das notas inseridas pelo usuário às variáveis
        n1 = Double.parseDouble(txtNota1.getText());
        n2 = Double.parseDouble(txtNota2.getText());
        n3 = Double.parseDouble(txtNota3.getText());
        n4 = Double.parseDouble(txtNota4.getText());
        
        //cálculo da média e exibição do resultado
        media = (n1 + n2 + n3 + n4)/4;  
        String MEDIA = mascara.format(media);
        lblMedia.setText("Média do Aluno: " + MEDIA);
        
        //verificação da maior nota
        if(n1 >= n2 && n1 >= n3 && n1 >= n4){
            lblMaiorNota.setText("Maior Nota: " + n1);
        } else if(n2 >= n1 && n2 >= n3 && n2 >= n4){
            lblMaiorNota.setText("Maior Nota: " + n2);
        } else if(n3 >= n1 && n3 >= n2 && n3 >= n4){
            lblMaiorNota.setText("Maior Nota: " + n3);
        } else if(n4 >= n1 && n4 >= n2 && n4 >= n3){
            lblMaiorNota.setText("Maior Nota: " + n4);
        }
        
        //verificação da menor nota
        if(n1 <= n2 && n1 <= n3 && n1 <= n4){
            lblMenorNota.setText("Menor Nota: " + n1);
        } else if(n2 <= n1 && n2 <= n3 && n2 <= n4){
            lblMenorNota.setText("Menor Nota: " + n2);
        } else if(n3 <= n1 && n3 <= n2 && n3 <= n4){
            lblMenorNota.setText("Menor Nota: " + n3);
        } else if(n4 <= n1 && n4 <= n2 && n4 <= n3){
            lblMenorNota.setText("Menor Nota: " + n4);
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        //limpando caixas de texto e colocando o foco da aplicação na primeira
        txtNota1.setText(null);
        txtNota2.setText(null);
        txtNota3.setText(null);
        txtNota4.setText(null);
        txtNota1.requestFocus();
        
        //limpando resultados anteriores
        lblMaiorNota.setText("Maior Nota:");
        lblMenorNota.setText("Menor Nota:");
        lblMedia.setText("Média do Aluno:");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        //confirmação para sair do programa
        int status = JOptionPane.showConfirmDialog(rootPane, "Deseja sair do sistema?", "Sair", JOptionPane.YES_NO_OPTION);
        if(status == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MediaAritmetica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MediaAritmetica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MediaAritmetica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MediaAritmetica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MediaAritmetica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSair;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblMaiorNota;
    private javax.swing.JLabel lblMedia;
    private javax.swing.JLabel lblMenorNota;
    private javax.swing.JLabel lblNota1;
    private javax.swing.JLabel lblNota2;
    private javax.swing.JLabel lblNota3;
    private javax.swing.JLabel lblNota4;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtNota1;
    private javax.swing.JTextField txtNota2;
    private javax.swing.JTextField txtNota3;
    private javax.swing.JTextField txtNota4;
    // End of variables declaration//GEN-END:variables
}
